name: Build PDF with Vivliostyle

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  vivliostyle-build:
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4 # こちらも v4 を推奨

      - name: Vivliostyle で PDF をビルド
        uses: vivliostyle/action@v1
        with:
          input: index.html
          artifact-name: generated-pdf

      - name: ビルドした PDF をアップロード
        uses: actions/upload-artifact@v4 # v4 に更新
        with:
          name: pdf-output
          path: output/*.pdf
