name: Build PDF with Vivliostyle

on:
  push:
    branches:
      - main  # ← `main` ブランチにプッシュされたら実行
  pull_request:

jobs:
  vivliostyle-build:
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v3
      
      - name: Vivliostyle で PDF をビルド
        uses: vivliostyle/action@v1
        with:
          artifact-name: generated-pdf  # アーティファクトの名前（変更可）

      - name: ビルドした PDF をアップロード
        uses: actions/upload-artifact@v3
        with:
          name: pdf-output
          path: output/*.pdf  # PDF の出力パスを変更する場合は適宜調整
